# Joint names
joint_names: [left_arm_joint_1, left_arm_joint_2, left_arm_joint_3, left_arm_joint_4, left_arm_joint_5, left_arm_joint_6]

# control_mode_adapter
max_command_silence: 0.5

# Creates the /joint_states topic necessary in ROS
left_arm_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

left_arm_joint_trajectory_controller:
  type: position_controllers/PilzJointTrajectoryController
  joints:
    - left_arm_joint_1
    - left_arm_joint_2
    - left_arm_joint_3
    - left_arm_joint_4
    - left_arm_joint_5
    - left_arm_joint_6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_arm_joint_1: {trajectory: 0.157, goal: 0.01}
      left_arm_joint_2: {trajectory: 0.157, goal: 0.01}
      left_arm_joint_3: {trajectory: 0.157, goal: 0.01}
      left_arm_joint_4: {trajectory: 0.157, goal: 0.01}
      left_arm_joint_5: {trajectory: 0.157, goal: 0.01}
      left_arm_joint_6: {trajectory: 0.157, goal: 0.01}
  stop_trajectory_duration: 0.2
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7