name: left_arm

bus:
  device: can1
sync:
  interval_ms: 10
  overflow: 0

defaults:
  eds_pkg: dualarm_exhibition
  eds_file: "config/prbt_0_1.dcf"

nodes:
  left_arm_joint_1:
    id: 3
    braketest_required: false
  left_arm_joint_2:
    id: 4
    braketest_required: false
  left_arm_joint_3:
    id: 5
    braketest_required: false
  left_arm_joint_4:
    id: 6
    braketest_required: false
  left_arm_joint_5:
    id: 7
    braketest_required: false
  left_arm_joint_6:
    id: 8
    braketest_required: false