left_arm:
  kinematics_solver: prbt_manipulator/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  link_prefix: left_arm_
right_arm:
  kinematics_solver: prbt_manipulator/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  link_prefix: right_arm_